version: 2.1

orbs:
  node: circleci/node@4.3.0

jobs:
  build:
    docker:
      - image: cimg/node:16.0.0-browsers
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - run: yarn --version

workflows:
  ci:
    jobs:
      - build
