version: 2.1

orbs:
  node: circleci/node@4.3.0
  codecov: codecov/codecov@1.1.5

jobs:
  tests:
    docker:
      - image: cimg/node:16.0.0-browsers
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
      - run: yarn cover
      - codecov/upload:
          file: coverage/*.json
  versioning:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run:
          name: Check package version
          command: node scripts/check-version jclebson autoescola

workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: main
            tags:
              ignore: /.*/
